version: '3.7'
services:
  postgres:
    image: postgres:9.6
    networks:
      - cisystem
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    restart: always
    ports:
      - 5432:5432
      
  sonarqube:
    build: .
    # image: sonarqube:9.9.1-community
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - cisystem
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
      SONAR_WEB_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=web
      SONAR_CE_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=ce
    restart: always
    depends_on: 
      - postgres

networks:
  cisystem:

volumes:
  postgres_data: