version: '3.3'
services:
  # gitlab:
  #   build: ./gitlab
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - cisystem
  jenkins:
    # image: jenkins/jenkins:lts
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - cisystem
    environment:
      JENKINS_HOME: /var/jenkins_home
      JENKINS_URL: http://localhost:8080/
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: password
      SONAR_USER: admin
      SONAR_PASSWORD: password
      SONAR_TOKEN: asdasdas
      SLACK_TEAM_DOMAIN: asdasd
    # volumes:
    #   - my_jenkins_home:/var/jenkins_home
    restart: always
  # postgres:
  #   image: postgres:9.6
  #   networks:
  #     - cisystem
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonarpasswd
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  # sonarqube:
  #   image: sonarqube:lts
  #   ports:
  #     - "9000:9000"
  #     - "9092:9092"
  #   networks:
  #     - cisystem
  #   environment:
  #     SONARQUBE_JDBC_USERNAME: sonar
  #     SONARQUBE_JDBC_PASSWORD: sonarpasswd
  #     SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
  #   depends_on: 
  #     - postgres

  # nexus:
  #   image: sonatype/nexus3:3.43.0
  #   volumes:
  #     - nexus_data:/sonatype-work
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - cisystem

networks:
  cisystem:

volumes:
  my_jenkins_home:
  postgres_data:
  nexus_data: